"""CPU latency benchmark of deployed graphs via ONNX Runtime (spec §5: 1 thread, batch 1, median).

    python -m nnfer.latency [--models a b c] [--runs 200] [--out results/latency.md]
"""
import argparse
import statistics
import tempfile
import time
from pathlib import Path

import numpy as np

from nnfer.complexity import count_flops, count_params
from nnfer.export import export_onnx
from nnfer.models import build_model

DEPLOYED = ["microexpnet", "mobilevit_xxs", "efficientface", "pattlite", "resnet18"]


def bench_onnx(onnx_path: Path, runs: int = 200, warmup: int = 30, threads: int = 1) -> dict:
    import onnxruntime as ort
    opt = ort.SessionOptions()
    opt.intra_op_num_threads = threads
    opt.inter_op_num_threads = 1
    sess = ort.InferenceSession(str(onnx_path), opt, providers=["CPUExecutionProvider"])
    x = np.zeros((1, 3, 112, 112), np.float32)
    for _ in range(warmup):
        sess.run(None, {"image": x})
    times = []
    for _ in range(runs):
        t0 = time.perf_counter()
        sess.run(None, {"image": x})
        times.append((time.perf_counter() - t0) * 1000)
    return {"median_ms": statistics.median(times), "p90_ms": statistics.quantiles(times, n=10)[8],
            "size_mb": onnx_path.stat().st_size / 1e6}


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--models", nargs="*", default=DEPLOYED)
    ap.add_argument("--runs", type=int, default=200)
    ap.add_argument("--out", default="results_remote/latency.md")
    a = ap.parse_args()
    lines = ["# CPU latency (ONNX Runtime, 1 thread, batch 1, 112x112; auto-generated by nnfer.latency)", "",
             "| model | params (M) | MFLOPs | ONNX (MB) | median (ms) | p90 (ms) |", "|---|---|---|---|---|---|"]
    with tempfile.TemporaryDirectory() as td:
        for name in a.models:
            m = build_model(name, 7, pretrained=False)
            p, f = count_params(m) / 1e6, count_flops(m) / 1e6
            onnx_path = export_onnx(name, None, Path(td) / f"{name}.onnx")
            r = bench_onnx(onnx_path, a.runs)
            lines.append(f"| {name} | {p:.3f} | {f:.1f} | {r['size_mb']:.2f} | {r['median_ms']:.2f} | {r['p90_ms']:.2f} |")
            print(lines[-1])
    out = Path(a.out).expanduser()
    out.parent.mkdir(parents=True, exist_ok=True)
    out.write_text("\n".join(lines) + "\n")


if __name__ == "__main__":
    main()
