"""Generate docs/data_stats.md from the cached manifests (no hand-typed numbers anywhere)."""
import argparse
from pathlib import Path

import pandas as pd

from nnfer.data.labels import FERPLUS_CLASSES, RAFDB_CLASSES

DATASETS = (("rafdb", RAFDB_CLASSES), ("ferplus", FERPLUS_CLASSES), ("ckplus", RAFDB_CLASSES),
            ("fer2013", RAFDB_CLASSES), ("sfew", RAFDB_CLASSES))


def build_report(cache_root: Path) -> str:
    lines = ["# Dataset statistics", "",
             "Auto-generated by `python -m data.report_stats`; do not edit by hand.", ""]
    for name, classes in DATASETS:
        p = cache_root / name / f"{name}_manifest.csv"
        if not p.exists():
            lines += [f"## {name}", "", "_cache not found_", ""]
            continue
        m = pd.read_csv(p)
        md5 = (cache_root / name / f"{name}_manifest.md5").read_text().strip()
        lines += [f"## {name}  (N={len(m)}, manifest md5 `{md5}`)", ""]
        tab = m.groupby(["split", "label"]).size().unstack(fill_value=0)
        tab.columns = [classes[c] for c in tab.columns]
        tab["total"] = tab.sum(axis=1)
        lines += [tab.to_markdown(), ""]
        if "near_neutral" in m:
            for tau in (0.2, 0.3, 0.4):
                m[f"nn@{tau}"] = (m.label != 0) & (m.neutral_share >= tau)
            nn = m.groupby("split")[[f"nn@{t}" for t in (0.2, 0.3, 0.4)]].sum()
            nn.columns = [f"near-neutral (tau={t})" for t in (0.2, 0.3, 0.4)]
            lines += ["Near-neutral ambiguous subset (majority != neutral, neutral vote share >= tau):", "",
                      nn.to_markdown(), ""]
            byc = m[m["nn@0.3"]].groupby("split").label.value_counts().unstack(fill_value=0)
            byc.columns = [classes[c] for c in byc.columns]
            lines += ["Near-neutral subset (tau=0.3) by majority class:", "", byc.to_markdown(), ""]
    return "\n".join(lines) + "\n"


def main():
    ap = argparse.ArgumentParser()
    ap.add_argument("--cache", default="~/haesung/data/cache")
    ap.add_argument("--out", default="docs/data_stats.md")
    a = ap.parse_args()
    report = build_report(Path(a.cache).expanduser())
    Path(a.out).parent.mkdir(parents=True, exist_ok=True)
    Path(a.out).write_text(report)
    print(report)


if __name__ == "__main__":
    main()
